apiVersion: v1
kind: Service
metadata:
  name: ignition-catalogs-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ignition-catalogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-catalogs-deployment
spec:
  selector:
    matchLabels:
      app: ignition-catalogs
  replicas: 1
  template:
    metadata:
      labels:
        app: ignition-catalogs
    spec:
      containers:
        - name: ignition-catalogs-api
          image: $CATALOGS_IMAGE:$VERSION
          ports:
            - containerPort: 8080
