[package]
name = "ignition-catalogs-wasm"
description = ""
version = "0.1.0"
authors = ["Theo Chupp"]

[profile.release]
debug = false
lto = true
opt-level = 's'

[lib]
crate-type = ["cdylib"]

[features]
default-features = ["console_error_panic_hook", "wee_alloc"]

[dependencies]
js-sys = "^0.3"

serde = "^1.0"
serde_derive = "^1.0"
bincode = "1.0"
base64 = "0.10"

itertools = "0.8"
reduce = "0.1"

cfg-if = "0.1"

weave = { git = "https://github.com/tchupp/ignition", rev = "c5fba6e8dace9636876d0d1c75690c3c781b39f2" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.1", optional = true }

[dependencies.wasm-bindgen]
version = "^0.2.29"
features = ["serde-serialize"]

[dev-dependencies]
maplit = "1.0"